/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SoberaniaRouteImport } from './routes/soberania'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndiceRouteImport } from './routes/indice'
import { Route as FormadoresRouteImport } from './routes/formadores'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as CorporativoRouteImport } from './routes/corporativo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoberaniaFormacaoRouteImport } from './routes/soberania_.formacao'
import { Route as SoberaniaEmpresasRouteImport } from './routes/soberania_.empresas'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicAdminLeadsRouteImport } from './routes/api/public/admin.leads'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SoberaniaRoute = SoberaniaRouteImport.update({
  id: '/soberania',
  path: '/soberania',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceRoute = IndiceRouteImport.update({
  id: '/indice',
  path: '/indice',
  getParentRoute: () => rootRouteImport,
} as any)
const FormadoresRoute = FormadoresRouteImport.update({
  id: '/formadores',
  path: '/formadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporativoRoute = CorporativoRouteImport.update({
  id: '/corporativo',
  path: '/corporativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoberaniaFormacaoRoute = SoberaniaFormacaoRouteImport.update({
  id: '/soberania_/formacao',
  path: '/soberania/formacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SoberaniaEmpresasRoute = SoberaniaEmpresasRouteImport.update({
  id: '/soberania_/empresas',
  path: '/soberania/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminLeadsRoute = ApiPublicAdminLeadsRouteImport.update({
  id: '/api/public/admin/leads',
  path: '/api/public/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/soberania/empresas': typeof SoberaniaEmpresasRoute
  '/soberania/formacao': typeof SoberaniaFormacaoRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/soberania/empresas': typeof SoberaniaEmpresasRoute
  '/soberania/formacao': typeof SoberaniaFormacaoRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/soberania_/empresas': typeof SoberaniaEmpresasRoute
  '/soberania_/formacao': typeof SoberaniaFormacaoRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/soberania/empresas'
    | '/soberania/formacao'
    | '/api/public/admin/leads'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/soberania/empresas'
    | '/soberania/formacao'
    | '/api/public/admin/leads'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/soberania_/empresas'
    | '/soberania_/formacao'
    | '/api/public/admin/leads'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporativoRoute: typeof CorporativoRoute
  EcossistemaRoute: typeof EcossistemaRoute
  EscolasRoute: typeof EscolasRoute
  FormadoresRoute: typeof FormadoresRoute
  IndiceRoute: typeof IndiceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoberaniaRoute: typeof SoberaniaRoute
  SobreRoute: typeof SobreRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  SoberaniaEmpresasRoute: typeof SoberaniaEmpresasRoute
  SoberaniaFormacaoRoute: typeof SoberaniaFormacaoRoute
  ApiPublicAdminLeadsRoute: typeof ApiPublicAdminLeadsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soberania': {
      id: '/soberania'
      path: '/soberania'
      fullPath: '/soberania'
      preLoaderRoute: typeof SoberaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice': {
      id: '/indice'
      path: '/indice'
      fullPath: '/indice'
      preLoaderRoute: typeof IndiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formadores': {
      id: '/formadores'
      path: '/formadores'
      fullPath: '/formadores'
      preLoaderRoute: typeof FormadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporativo': {
      id: '/corporativo'
      path: '/corporativo'
      fullPath: '/corporativo'
      preLoaderRoute: typeof CorporativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soberania_/formacao': {
      id: '/soberania_/formacao'
      path: '/soberania/formacao'
      fullPath: '/soberania/formacao'
      preLoaderRoute: typeof SoberaniaFormacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soberania_/empresas': {
      id: '/soberania_/empresas'
      path: '/soberania/empresas'
      fullPath: '/soberania/empresas'
      preLoaderRoute: typeof SoberaniaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/leads': {
      id: '/api/public/admin/leads'
      path: '/api/public/admin/leads'
      fullPath: '/api/public/admin/leads'
      preLoaderRoute: typeof ApiPublicAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporativoRoute: CorporativoRoute,
  EcossistemaRoute: EcossistemaRoute,
  EscolasRoute: EscolasRoute,
  FormadoresRoute: FormadoresRoute,
  IndiceRoute: IndiceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoberaniaRoute: SoberaniaRoute,
  SobreRoute: SobreRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  SoberaniaEmpresasRoute: SoberaniaEmpresasRoute,
  SoberaniaFormacaoRoute: SoberaniaFormacaoRoute,
  ApiPublicAdminLeadsRoute: ApiPublicAdminLeadsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
