/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SoberaniaRouteImport } from './routes/soberania'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndiceRouteImport } from './routes/indice'
import { Route as FormadoresRouteImport } from './routes/formadores'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as CorporativoRouteImport } from './routes/corporativo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as ApiPublicAdminLeadsRouteImport } from './routes/api/public/admin.leads'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SoberaniaRoute = SoberaniaRouteImport.update({
  id: '/soberania',
  path: '/soberania',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceRoute = IndiceRouteImport.update({
  id: '/indice',
  path: '/indice',
  getParentRoute: () => rootRouteImport,
} as any)
const FormadoresRoute = FormadoresRouteImport.update({
  id: '/formadores',
  path: '/formadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporativoRoute = CorporativoRouteImport.update({
  id: '/corporativo',
  path: '/corporativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminLeadsRoute = ApiPublicAdminLeadsRouteImport.update({
  id: '/api/public/admin/leads',
  path: '/api/public/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporativo': typeof CorporativoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/escolas': typeof EscolasRoute
  '/formadores': typeof FormadoresRoute
  '/indice': typeof IndiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soberania': typeof SoberaniaRoute
  '/sobre': typeof SobreRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/public/admin/leads': typeof ApiPublicAdminLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/api/public/admin/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/api/public/admin/leads'
  id:
    | '__root__'
    | '/'
    | '/corporativo'
    | '/ecossistema'
    | '/escolas'
    | '/formadores'
    | '/indice'
    | '/sitemap.xml'
    | '/soberania'
    | '/sobre'
    | '/admin/leads'
    | '/api/public/admin/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporativoRoute: typeof CorporativoRoute
  EcossistemaRoute: typeof EcossistemaRoute
  EscolasRoute: typeof EscolasRoute
  FormadoresRoute: typeof FormadoresRoute
  IndiceRoute: typeof IndiceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoberaniaRoute: typeof SoberaniaRoute
  SobreRoute: typeof SobreRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  ApiPublicAdminLeadsRoute: typeof ApiPublicAdminLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soberania': {
      id: '/soberania'
      path: '/soberania'
      fullPath: '/soberania'
      preLoaderRoute: typeof SoberaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice': {
      id: '/indice'
      path: '/indice'
      fullPath: '/indice'
      preLoaderRoute: typeof IndiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formadores': {
      id: '/formadores'
      path: '/formadores'
      fullPath: '/formadores'
      preLoaderRoute: typeof FormadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporativo': {
      id: '/corporativo'
      path: '/corporativo'
      fullPath: '/corporativo'
      preLoaderRoute: typeof CorporativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/leads': {
      id: '/api/public/admin/leads'
      path: '/api/public/admin/leads'
      fullPath: '/api/public/admin/leads'
      preLoaderRoute: typeof ApiPublicAdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporativoRoute: CorporativoRoute,
  EcossistemaRoute: EcossistemaRoute,
  EscolasRoute: EscolasRoute,
  FormadoresRoute: FormadoresRoute,
  IndiceRoute: IndiceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoberaniaRoute: SoberaniaRoute,
  SobreRoute: SobreRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  ApiPublicAdminLeadsRoute: ApiPublicAdminLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
